version: '3.8'
services:
  postgres:
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pagila-data:/var/lib/postgresql/data
      - ./pagila.sql:/docker-entrypoint-initdb.d/pagila.sql
volumes:
  pagila-data: